/*
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FinetuneCompletionRequestInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FinetuneCompletionRequestInput{}

// FinetuneCompletionRequestInput The per-line training example of a fine-tuning input file for completions models
type FinetuneCompletionRequestInput struct {
	// The input prompt for this training example.
	Prompt *string `json:"prompt,omitempty"`
	// The desired completion for this training example.
	Completion *string `json:"completion,omitempty"`
}

// NewFinetuneCompletionRequestInput instantiates a new FinetuneCompletionRequestInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinetuneCompletionRequestInput() *FinetuneCompletionRequestInput {
	this := FinetuneCompletionRequestInput{}
	return &this
}

// NewFinetuneCompletionRequestInputWithDefaults instantiates a new FinetuneCompletionRequestInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinetuneCompletionRequestInputWithDefaults() *FinetuneCompletionRequestInput {
	this := FinetuneCompletionRequestInput{}
	return &this
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *FinetuneCompletionRequestInput) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinetuneCompletionRequestInput) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *FinetuneCompletionRequestInput) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *FinetuneCompletionRequestInput) SetPrompt(v string) {
	o.Prompt = &v
}

// GetCompletion returns the Completion field value if set, zero value otherwise.
func (o *FinetuneCompletionRequestInput) GetCompletion() string {
	if o == nil || IsNil(o.Completion) {
		var ret string
		return ret
	}
	return *o.Completion
}

// GetCompletionOk returns a tuple with the Completion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinetuneCompletionRequestInput) GetCompletionOk() (*string, bool) {
	if o == nil || IsNil(o.Completion) {
		return nil, false
	}
	return o.Completion, true
}

// HasCompletion returns a boolean if a field has been set.
func (o *FinetuneCompletionRequestInput) HasCompletion() bool {
	if o != nil && !IsNil(o.Completion) {
		return true
	}

	return false
}

// SetCompletion gets a reference to the given string and assigns it to the Completion field.
func (o *FinetuneCompletionRequestInput) SetCompletion(v string) {
	o.Completion = &v
}

func (o FinetuneCompletionRequestInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinetuneCompletionRequestInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.Completion) {
		toSerialize["completion"] = o.Completion
	}
	return toSerialize, nil
}

type NullableFinetuneCompletionRequestInput struct {
	value *FinetuneCompletionRequestInput
	isSet bool
}

func (v NullableFinetuneCompletionRequestInput) Get() *FinetuneCompletionRequestInput {
	return v.value
}

func (v *NullableFinetuneCompletionRequestInput) Set(val *FinetuneCompletionRequestInput) {
	v.value = val
	v.isSet = true
}

func (v NullableFinetuneCompletionRequestInput) IsSet() bool {
	return v.isSet
}

func (v *NullableFinetuneCompletionRequestInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinetuneCompletionRequestInput(val *FinetuneCompletionRequestInput) *NullableFinetuneCompletionRequestInput {
	return &NullableFinetuneCompletionRequestInput{value: val, isSet: true}
}

func (v NullableFinetuneCompletionRequestInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinetuneCompletionRequestInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


