/*
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ChatCompletionRequestToolMessageContent - The contents of the tool message.
type ChatCompletionRequestToolMessageContent struct {
	ArrayOfChatCompletionRequestToolMessageContentPart *[]ChatCompletionRequestToolMessageContentPart
	String *string
}

// []ChatCompletionRequestToolMessageContentPartAsChatCompletionRequestToolMessageContent is a convenience function that returns []ChatCompletionRequestToolMessageContentPart wrapped in ChatCompletionRequestToolMessageContent
func ArrayOfChatCompletionRequestToolMessageContentPartAsChatCompletionRequestToolMessageContent(v *[]ChatCompletionRequestToolMessageContentPart) ChatCompletionRequestToolMessageContent {
	return ChatCompletionRequestToolMessageContent{
		ArrayOfChatCompletionRequestToolMessageContentPart: v,
	}
}

// stringAsChatCompletionRequestToolMessageContent is a convenience function that returns string wrapped in ChatCompletionRequestToolMessageContent
func StringAsChatCompletionRequestToolMessageContent(v *string) ChatCompletionRequestToolMessageContent {
	return ChatCompletionRequestToolMessageContent{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ChatCompletionRequestToolMessageContent) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfChatCompletionRequestToolMessageContentPart
	err = newStrictDecoder(data).Decode(&dst.ArrayOfChatCompletionRequestToolMessageContentPart)
	if err == nil {
		jsonArrayOfChatCompletionRequestToolMessageContentPart, _ := json.Marshal(dst.ArrayOfChatCompletionRequestToolMessageContentPart)
		if string(jsonArrayOfChatCompletionRequestToolMessageContentPart) == "{}" { // empty struct
			dst.ArrayOfChatCompletionRequestToolMessageContentPart = nil
		} else {
			if err = validator.Validate(dst.ArrayOfChatCompletionRequestToolMessageContentPart); err != nil {
				dst.ArrayOfChatCompletionRequestToolMessageContentPart = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfChatCompletionRequestToolMessageContentPart = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfChatCompletionRequestToolMessageContentPart = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ChatCompletionRequestToolMessageContent)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ChatCompletionRequestToolMessageContent)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ChatCompletionRequestToolMessageContent) MarshalJSON() ([]byte, error) {
	if src.ArrayOfChatCompletionRequestToolMessageContentPart != nil {
		return json.Marshal(&src.ArrayOfChatCompletionRequestToolMessageContentPart)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ChatCompletionRequestToolMessageContent) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfChatCompletionRequestToolMessageContentPart != nil {
		return obj.ArrayOfChatCompletionRequestToolMessageContentPart
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableChatCompletionRequestToolMessageContent struct {
	value *ChatCompletionRequestToolMessageContent
	isSet bool
}

func (v NullableChatCompletionRequestToolMessageContent) Get() *ChatCompletionRequestToolMessageContent {
	return v.value
}

func (v *NullableChatCompletionRequestToolMessageContent) Set(val *ChatCompletionRequestToolMessageContent) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionRequestToolMessageContent) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionRequestToolMessageContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionRequestToolMessageContent(val *ChatCompletionRequestToolMessageContent) *NullableChatCompletionRequestToolMessageContent {
	return &NullableChatCompletionRequestToolMessageContent{value: val, isSet: true}
}

func (v NullableChatCompletionRequestToolMessageContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionRequestToolMessageContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


