/*
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// RealtimeSessionMaxResponseOutputTokens - Maximum number of output tokens for a single assistant response, inclusive of tool calls. Provide an integer between 1 and 4096 to limit output tokens, or `inf` for the maximum available tokens for a given model. Defaults to `inf`. 
type RealtimeSessionMaxResponseOutputTokens struct {
	Int32 *int32
	String *string
}

// int32AsRealtimeSessionMaxResponseOutputTokens is a convenience function that returns int32 wrapped in RealtimeSessionMaxResponseOutputTokens
func Int32AsRealtimeSessionMaxResponseOutputTokens(v *int32) RealtimeSessionMaxResponseOutputTokens {
	return RealtimeSessionMaxResponseOutputTokens{
		Int32: v,
	}
}

// stringAsRealtimeSessionMaxResponseOutputTokens is a convenience function that returns string wrapped in RealtimeSessionMaxResponseOutputTokens
func StringAsRealtimeSessionMaxResponseOutputTokens(v *string) RealtimeSessionMaxResponseOutputTokens {
	return RealtimeSessionMaxResponseOutputTokens{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RealtimeSessionMaxResponseOutputTokens) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RealtimeSessionMaxResponseOutputTokens)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RealtimeSessionMaxResponseOutputTokens)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RealtimeSessionMaxResponseOutputTokens) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RealtimeSessionMaxResponseOutputTokens) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRealtimeSessionMaxResponseOutputTokens struct {
	value *RealtimeSessionMaxResponseOutputTokens
	isSet bool
}

func (v NullableRealtimeSessionMaxResponseOutputTokens) Get() *RealtimeSessionMaxResponseOutputTokens {
	return v.value
}

func (v *NullableRealtimeSessionMaxResponseOutputTokens) Set(val *RealtimeSessionMaxResponseOutputTokens) {
	v.value = val
	v.isSet = true
}

func (v NullableRealtimeSessionMaxResponseOutputTokens) IsSet() bool {
	return v.isSet
}

func (v *NullableRealtimeSessionMaxResponseOutputTokens) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealtimeSessionMaxResponseOutputTokens(val *RealtimeSessionMaxResponseOutputTokens) *NullableRealtimeSessionMaxResponseOutputTokens {
	return &NullableRealtimeSessionMaxResponseOutputTokens{value: val, isSet: true}
}

func (v NullableRealtimeSessionMaxResponseOutputTokens) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealtimeSessionMaxResponseOutputTokens) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


