/*
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ChatCompletionRequestToolMessageContentPart - struct for ChatCompletionRequestToolMessageContentPart
type ChatCompletionRequestToolMessageContentPart struct {
	ChatCompletionRequestMessageContentPartText *ChatCompletionRequestMessageContentPartText
}

// ChatCompletionRequestMessageContentPartTextAsChatCompletionRequestToolMessageContentPart is a convenience function that returns ChatCompletionRequestMessageContentPartText wrapped in ChatCompletionRequestToolMessageContentPart
func ChatCompletionRequestMessageContentPartTextAsChatCompletionRequestToolMessageContentPart(v *ChatCompletionRequestMessageContentPartText) ChatCompletionRequestToolMessageContentPart {
	return ChatCompletionRequestToolMessageContentPart{
		ChatCompletionRequestMessageContentPartText: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ChatCompletionRequestToolMessageContentPart) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ChatCompletionRequestMessageContentPartText
	err = newStrictDecoder(data).Decode(&dst.ChatCompletionRequestMessageContentPartText)
	if err == nil {
		jsonChatCompletionRequestMessageContentPartText, _ := json.Marshal(dst.ChatCompletionRequestMessageContentPartText)
		if string(jsonChatCompletionRequestMessageContentPartText) == "{}" { // empty struct
			dst.ChatCompletionRequestMessageContentPartText = nil
		} else {
			if err = validator.Validate(dst.ChatCompletionRequestMessageContentPartText); err != nil {
				dst.ChatCompletionRequestMessageContentPartText = nil
			} else {
				match++
			}
		}
	} else {
		dst.ChatCompletionRequestMessageContentPartText = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ChatCompletionRequestMessageContentPartText = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ChatCompletionRequestToolMessageContentPart)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ChatCompletionRequestToolMessageContentPart)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ChatCompletionRequestToolMessageContentPart) MarshalJSON() ([]byte, error) {
	if src.ChatCompletionRequestMessageContentPartText != nil {
		return json.Marshal(&src.ChatCompletionRequestMessageContentPartText)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ChatCompletionRequestToolMessageContentPart) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ChatCompletionRequestMessageContentPartText != nil {
		return obj.ChatCompletionRequestMessageContentPartText
	}

	// all schemas are nil
	return nil
}

type NullableChatCompletionRequestToolMessageContentPart struct {
	value *ChatCompletionRequestToolMessageContentPart
	isSet bool
}

func (v NullableChatCompletionRequestToolMessageContentPart) Get() *ChatCompletionRequestToolMessageContentPart {
	return v.value
}

func (v *NullableChatCompletionRequestToolMessageContentPart) Set(val *ChatCompletionRequestToolMessageContentPart) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionRequestToolMessageContentPart) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionRequestToolMessageContentPart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionRequestToolMessageContentPart(val *ChatCompletionRequestToolMessageContentPart) *NullableChatCompletionRequestToolMessageContentPart {
	return &NullableChatCompletionRequestToolMessageContentPart{value: val, isSet: true}
}

func (v NullableChatCompletionRequestToolMessageContentPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionRequestToolMessageContentPart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


